---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client
