---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: http-server
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/namespaces/http-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client
