---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./kubernetes/namespaces/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
  validation: client
